name: Build TelegramX

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Telegram X
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_HOME" >> local.properties
        echo "telegram.api_id=${{ secrets.TELEGRAM_API_ID }}" >> local.properties
        echo "telegram.api_hash=${{ secrets.TELEGRAM_API_HASH }}" >> local.properties
        echo "keystore.file=${{ secrets.KEYSTORE_FILE }}" >> local.properties
        echo "keystore.password=${{ secrets.KEYSTORE_PASSWORD }}" >> local.properties
        echo "key.alias=${{ secrets.KEY_ALIAS }}" >> local.properties
        echo "key.password=${{ secrets.KEY_PASSWORD }}" >> local.properties

    - name: Set executable permissions for setup script
      run: chmod +x scripts/setup.sh

    - name: Run setup script
      run: |
         export TERM=xterm
         ./scripts/setup.sh

    - name: Build Telegram X
      run: ./gradlew assembleUniversalRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: TelegramX-APK
        path: app/build/outputs/apk/universal/release/*.apk
