name: Build Telegram X

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Keystore
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > keystore.jks
        echo -e "keystore.file=$(pwd)/keystore.jks\nkeystore.password=${{ secrets.KEYSTORE_PASSWORD }}\nkey.alias=${{ secrets.KEY_ALIAS }}\nkey.password=${{ secrets.KEY_PASSWORD }}" > keystore.properties

    - name: Build APK
      run: ./gradlew assembleUniversalRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Universal-Release-APK
        path: app/build/outputs/apk/universal/release/*.apk
