name: Build Telegram X

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 31
        target: default
        arch: x86_64

    - name: Setup local.properties
      run: echo "sdk.dir=$ANDROID_SDK_ROOT" >> local.properties

    - name: Setup keystore.properties
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > keystore.jks
        echo "keystore.file=$(pwd)/keystore.jks" >> keystore.properties
        echo "keystore.password=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
        echo "key.alias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
        echo "key.password=${{ secrets.KEY_PASSWORD }}" >> keystore.properties

    - name: Build APK
      run: ./gradlew assembleUniversalRelease
